name: octomobile
description: "OCTO Mobile Banking App."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10
  http: ^1.2.0
  shared_preferences: ^2.5.5
  flutter_typeahead: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon-wishlist.svg
    - assets/icon-search.svg
    - assets/icon-notification.svg
    - assets/icon-logout.svg
    - assets/gopay-logo.svg
    - assets/icons/
    - assets/banner/
    - assets/background/
    - assets/octo/

  fonts:                                     
    - family: Calibri
      fonts:
        - asset: assets/fonts/calibri-regular.ttf
          weight: 400
        - asset: assets/fonts/calibri-bold.ttf
          weight: 700
        - asset: assets/fonts/calibri-italic.ttf
          style: italic
        - asset: assets/fonts/calibri-bold-italic.ttf
          weight: 700
          style: italic